//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalabiyauQuotation.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalabiyauQuotation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 一个用于快捷粘贴随机喵语的小工具喵~ 的本地化字符串。
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 喵语生成器 的本地化字符串。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 喵语生成器 By 香草味的纳西妲喵(VanillaNahida) 的本地化字符串。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序作者: 香草味的纳西妲喵(VanillaNahida) 的本地化字符串。
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者B站主页 的本地化字符串。
        /// </summary>
        public static string BilibiliHomepage {
            get {
                return ResourceManager.GetString("BilibiliHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一键复制喵 的本地化字符串。
        /// </summary>
        public static string BtnCopy {
            get {
                return ResourceManager.GetString("BtnCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动更新词库 的本地化字符串。
        /// </summary>
        public static string BtnDownload {
            get {
                return ResourceManager.GetString("BtnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 换一个喵 的本地化字符串。
        /// </summary>
        public static string BtnGenerate {
            get {
                return ResourceManager.GetString("BtnGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存设置 的本地化字符串。
        /// </summary>
        public static string BtnSaveSettings {
            get {
                return ResourceManager.GetString("BtnSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动发送（粘贴后按下Enter） 的本地化字符串。
        /// </summary>
        public static string ChkAutoSend {
            get {
                return ResourceManager.GetString("ChkAutoSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空输入框并重新粘贴 的本地化字符串。
        /// </summary>
        public static string ChkClearAndPaste {
            get {
                return ResourceManager.GetString("ChkClearAndPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动时自动更新词库 的本地化字符串。
        /// </summary>
        public static string ChkEnableAutoDownload {
            get {
                return ResourceManager.GetString("ChkEnableAutoDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GitHub仓库 的本地化字符串。
        /// </summary>
        public static string GitHubRepo {
            get {
                return ResourceManager.GetString("GitHubRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 词库设置 的本地化字符串。
        /// </summary>
        public static string GroupDictionary {
            get {
                return ResourceManager.GetString("GroupDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局粘贴快捷键设置 的本地化字符串。
        /// </summary>
        public static string GroupGlobalHotkey {
            get {
                return ResourceManager.GetString("GroupGlobalHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 界面语言设置（Language Settings） 的本地化字符串。
        /// </summary>
        public static string GroupLanguage {
            get {
                return ResourceManager.GetString("GroupLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 随机喵语 的本地化字符串。
        /// </summary>
        public static string GroupRandomCatLanguage {
            get {
                return ResourceManager.GetString("GroupRandomCatLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示：推荐使用包含 Ctrl、Alt、Shift 或 Win 的组合键以避免与系统快捷键冲突 的本地化字符串。
        /// </summary>
        public static string HintHotkey {
            get {
                return ResourceManager.GetString("HintHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 词库地址: 的本地化字符串。
        /// </summary>
        public static string LabelDictionaryUrl {
            get {
                return ResourceManager.GetString("LabelDictionaryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快捷键: 的本地化字符串。
        /// </summary>
        public static string LabelHotkey {
            get {
                return ResourceManager.GetString("LabelHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 界面语言（Language）: 的本地化字符串。
        /// </summary>
        public static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动（跟随系统） 的本地化字符串。
        /// </summary>
        public static string LanguageAuto {
            get {
                return ResourceManager.GetString("LanguageAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        public static string LanguageChinese {
            get {
                return ResourceManager.GetString("LanguageChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string MenuItemExit {
            get {
                return ResourceManager.GetString("MenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示主界面 的本地化字符串。
        /// </summary>
        public static string MenuItemShow {
            get {
                return ResourceManager.GetString("MenuItemShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言设置已更改，需要重启程序才能生效。是否立即重启？ 的本地化字符串。
        /// </summary>
        public static string MsgRestartRequired {
            get {
                return ResourceManager.GetString("MsgRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要重启 的本地化字符串。
        /// </summary>
        public static string MsgRestartRequiredTitle {
            get {
                return ResourceManager.GetString("MsgRestartRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置已保存喵 的本地化字符串。
        /// </summary>
        public static string MsgSettingsSaved {
            get {
                return ResourceManager.GetString("MsgSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string MsgSettingsSavedTitle {
            get {
                return ResourceManager.GetString("MsgSettingsSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 饱饱窝会一直的看着你…… 的本地化字符串。
        /// </summary>
        public static string NotificationMessage {
            get {
                return ResourceManager.GetString("NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已最小化到系统托盘喵~ 的本地化字符串。
        /// </summary>
        public static string NotificationMinimized {
            get {
                return ResourceManager.GetString("NotificationMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星绘 的本地化字符串。
        /// </summary>
        public static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 香草の小黑屋（B站一群）：621457510 的本地化字符串。
        /// </summary>
        public static string QQGroup1 {
            get {
                return ResourceManager.GetString("QQGroup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 香草的技术部（B站二群）：1031065631 的本地化字符串。
        /// </summary>
        public static string QQGroup2 {
            get {
                return ResourceManager.GetString("QQGroup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 香草的AI工坊（B站三群）：195260107 的本地化字符串。
        /// </summary>
        public static string QQGroup3 {
            get {
                return ResourceManager.GetString("QQGroup3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 香草的Ubuntu服务器小屋（B站四群）：1074471035 的本地化字符串。
        /// </summary>
        public static string QQGroup4 {
            get {
                return ResourceManager.GetString("QQGroup4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 香草的喵喵军团：1067451762 的本地化字符串。
        /// </summary>
        public static string QQGroup5 {
            get {
                return ResourceManager.GetString("QQGroup5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纳西妲厨聚集地：814061421 的本地化字符串。
        /// </summary>
        public static string QQGroup6 {
            get {
                return ResourceManager.GetString("QQGroup6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加入作者的QQ群喵（点我前往群组列表） 的本地化字符串。
        /// </summary>
        public static string QQGroups {
            get {
                return ResourceManager.GetString("QQGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已更换喵语文本~ 的本地化字符串。
        /// </summary>
        public static string StatusChanged {
            get {
                return ResourceManager.GetString("StatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已更换并粘贴喵语文本 的本地化字符串。
        /// </summary>
        public static string StatusChangedAndPasted {
            get {
                return ResourceManager.GetString("StatusChangedAndPasted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已复制到剪贴板喵 的本地化字符串。
        /// </summary>
        public static string StatusCopied {
            get {
                return ResourceManager.GetString("StatusCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 词库下载失败！ 的本地化字符串。
        /// </summary>
        public static string StatusDownloadFailed {
            get {
                return ResourceManager.GetString("StatusDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 词库下载失败：词库格式不合法！ 的本地化字符串。
        /// </summary>
        public static string StatusDownloadFailedFormat {
            get {
                return ResourceManager.GetString("StatusDownloadFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载词库... 的本地化字符串。
        /// </summary>
        public static string StatusDownloading {
            get {
                return ResourceManager.GetString("StatusDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 词库下载成功，共 {0} 条 的本地化字符串。
        /// </summary>
        public static string StatusDownloadSuccess {
            get {
                return ResourceManager.GetString("StatusDownloadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已加载 {0} 条喵语文本 的本地化字符串。
        /// </summary>
        public static string StatusLoaded {
            get {
                return ResourceManager.GetString("StatusLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先设置词库地址喵！ 的本地化字符串。
        /// </summary>
        public static string StatusNoDictionaryUrl {
            get {
                return ResourceManager.GetString("StatusNoDictionaryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就绪 的本地化字符串。
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已准备就绪喵 的本地化字符串。
        /// </summary>
        public static string StatusReadyAgain {
            get {
                return ResourceManager.GetString("StatusReadyAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有尚未保存的更改喵！ 的本地化字符串。
        /// </summary>
        public static string StatusUnsavedChanges {
            get {
                return ResourceManager.GetString("StatusUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string TabAbout {
            get {
                return ResourceManager.GetString("TabAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主界面 的本地化字符串。
        /// </summary>
        public static string TabMain {
            get {
                return ResourceManager.GetString("TabMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宝宝我会一直的看着你喵~ 的本地化字符串。
        /// </summary>
        public static string TaskbarTooltip {
            get {
                return ResourceManager.GetString("TaskbarTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本: 1.0.1 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
